version: '3'
services:
  mysqldb:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: mysqldb-catalog-service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: catalog